### ISSUE TITLE
Adding `NewRelic.Phoenix.Instrumenter` kills local error reporting

### ISSUE THREAD

**Issue by coladarci** [binaryseed/new_relic_phoenix#10]
Hey all - we just added new relic to our app and all worked well but noticed that we lost all stack traces for our 500s when doing LOCAL development. We are on the latest version of Phoenix, new relic and this package. 

The stacktraces disapear the moment we add `NewRelic.Phoenix.Instrumenter` to our `instrumenters` config of our `Endpoint`.

Are we missing something obvious?

**Comment by binaryseed** [comment]
This package will be retired in the future in favor of `telemetry` based instrumentation, so I'm not going to address this. Thanks for reporting though!
