### ISSUE TITLE
mix test task fails

### ISSUE THREAD

**Issue by patatoid** [binaryseed/new_relic_phoenix#11]
After adding and configuring New Relic, my `mix test` tasks fail with the following error
```
     ** (exit) exited in: GenServer.call(NewRelic.Transaction.Monitor, {:add, #PID<0.1211.0>}, 5000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

I succeed to make it work by adding `:new_relic_phoenix` as an extra application in `mix.exs`.

Could be good to add that configuration in README, or am I wrong by doing that ?

**Comment by binaryseed** [comment]
You probably need to migrate away from using the `applications` key in your application or check that the agent is not excluded from the `test` environment
