### ISSUE TITLE
Usage of instrumenters in deprecated in Phoenix 1.5

### ISSUE THREAD

**Issue by VitorTrin** [binaryseed/new_relic_phoenix#19]
If you configure the instrumenter in Phoenix 1.5  you receive the following warning

```
:instrumenters configuration for MyApp.Endpoint is deprecated and has no effect
```

Should we upgrade to Phoenix 1.5 even through we use this lib?

**Comment by binaryseed** [comment]
Phoenix instrumentation will be provided by the agent itself once it adopts `telemetry` for Plug..

That work is in progress in https://github.com/newrelic/elixir_agent/pull/241 but will take some time...

**Comment by anderkonzen** [comment]
Hello! Any workarounds meanwhile?

**Comment by iv-mexx** [comment]
@binaryseed Are you saying that `new_relic_phoenix` will be obsolete then?

**Comment by binaryseed** [comment]
Yes

**Comment by yukster** [comment]
@binaryseed the PR you mentioned has been closed w/o merging. Are there plans to get NewRelic agent working for Phoenix 1.5?

**Comment by binaryseed** [comment]
That PR was replaced by https://github.com/newrelic/elixir_agent/pull/284 which includes notes about `rc` releases that are available...

**Comment by yukster** [comment]
Thanks!

**Comment by binaryseed** [comment]
FYI, one step closer: #22
