### ISSUE TITLE
NewRelic PID category

### ISSUE THREAD

**Issue by ivanovv** [binaryseed/new_relic_phoenix#20]
I have a very straightforward controller code

```elixir
  def create(conn, %{"channel" => channel, "data" => data, "event" => event} = params) do
    ChatWeb.Endpoint.broadcast!(channel, "msg", params)

    json(conn, %{channel: channel, data: data, event: event})
  end
```

Mostly it takes 2-5ms, but sometimes it takes ~200-300ms and then I see a transaction trace in NewRelic

The breakdown looks like this:

![Screenshot 2020-12-18 at 23 21 07](https://user-images.githubusercontent.com/142624/102656256-02512a80-418d-11eb-805c-0e19cb366128.png)

What is this `#PID<0.XXX.YYY>` thing? the time spent waiting to spawn and wait for the process? Or the time it took that process to answer?

Thank you!

**Comment by binaryseed** [comment]
That is a process that is spawned from within the Transaction

**Comment by ivanovv** [comment]
Interesting!

I looked at additional data that NewRElic shows, and there a table at the bottom (`Transaction attributes`), which also has `pid`, and that `pid` matches the `#PID` from the above screenshot (not exactly that pid ofc, but I guess you get the idea)

I seriously doubt that NewRelic would capture some random spawned process pid and put it in the `Transaction attributes`
