### ISSUE TITLE
Phoenix 1.4 is out

### ISSUE THREAD

**Issue by fbjork** [binaryseed/new_relic_phoenix#3]
https://phoenixframework.org/blog/phoenix-1-4-0-released

Would be good to see the dependency bumped.

Also, are you planning on moving this repo under the newrelic org?

**Comment by binaryseed** [comment]
This is complete since https://github.com/binaryseed/new_relic_phoenix/commit/5d253d3838ce032d75e3a6cdc1a7bf83a4a2d22c
