### ISSUE TITLE
Absence of data in Conn causes errors

### ISSUE THREAD

**Issue by IcyEagle** [binaryseed/new_relic_phoenix#9]
When an error occurred (NoRouteError for example) the module is crashed with the next error message:

`{function_clause, [{'Elixir.NewRelic.Transaction.Complete', transform_name_attrs...`

As far as I see there are some matchings for `transform_name_attrs` but none of them correspond. I followed your guide to inject NewRelic into my Endpoint but it still doesn't work.

My deps:
```
{:phoenix, "~> 1.4"},
{:cowboy, "~> 2.5"},
{:plug_cowboy, "~> 2.0"},
{:new_relic_agent, "~> 1.4"},
{:new_relic_phoenix, "~> 0.1"},
```

**Comment by binaryseed** [comment]
These types of issues are fixed in later agent versions... current is `1.19`
